### ISSUE TITLE
如何取得message ID？

### ISSUE THREAD

**Issue by Amaodemao** [ezioruan/midjourney-python-api#2]
如题，在使用example.py进行配置之后不知道该如何自动获取messageID，没法实现自动化的interact

**Comment by ezioruan** [comment]
这是异步的模式， 可以配合开个http server ，或者可以加个队列  收到消息 扔到队列 ， 收消息 执行interact。

**Comment by ezioruan** [comment]
这是异步的模式， 可以配合开个http server ，或者可以加个队列  收到消息 扔到队列 ， 收消息 执行interact。

**Comment by Amaodemao** [comment]
谢谢，我去尝试一下
