### ISSUE TITLE
Help me with the data the script needs

### ISSUE THREAD

**Issue by TrueGodOfHyperdeath** [ezioruan/midjourney-python-api#4]
```
client = MidjourneyClient(
        name="test",
        token="",  # your discord token
        application_id="",  # bot application_id
        guild_id="",  # your discord server id or None
        channel_id="",  # your channel_id
        message_handler=process_message,
    )

```    
    
"name" - any name?
"token" - the token of your discord account?
"application_id" - id of midjourney bot?
"guild_id" - id of my discord server?
"channel_id" - chat id where requests will be generated?
"message_handler" - request text for image generation?
    
**Did I understand correctly?**

**Comment by ezioruan** [comment]
yes, you are right

**Comment by TrueGodOfHyperdeath** [comment]
@ezioruan thank you

**Comment by ezioruan** [comment]
you are welcome @TrueGodOfHyperdeath

**Comment by makkarss929** [comment]
Hi can provide me example of input ?
